package com.example.tobias.werwolf_v1

import com.example.tobias.werwolf_v1.database.models.CharacterClass

class NightRepository {

    fun generateCharacters(): ArrayList<CharacterClass> {       // todo load from db
        return arrayListOf(
            CharacterClass(
                "Werwolf",
                "blabla",
                R.color.werwolf,
                true,
                true,
                R.string.night_desc_werwolf
            ),
            CharacterClass(
                "Bürger",
                "blabla",
                R.color.citizen,
                true,
                false,
                R.string.night_desc_citizen
            ),
            CharacterClass(
                "Amor",
                "blabla",
                R.color.amor,
                false,
                false,
                R.string.night_desc_armor
            ),
            CharacterClass(
                "Hexe",
                "blabla",
                R.color.witch,
                false,
                false,
                R.string.night_desc_witch
            ),
            CharacterClass(
                "Wächter",
                "blabla",
                R.color.guradian,
                false,
                false,
                R.string.night_desc_guardian
            ),
            CharacterClass(
                "Mädchen",
                "blabla",
                R.color.girl,
                false,
                false,
                R.string.night_desc_girl
            ),
            CharacterClass(
                "Seher",
                "blabla",
                R.color.seher,
                false,
                false,
                R.string.night_desc_seher
            ),
            CharacterClass(
                "Dieb",
                "blabla",
                R.color.thief,
                false,
                false,
                R.string.night_desc_thief
            ),
            CharacterClass(
                "Jäger",
                "blabla",
                R.color.hunter,
                false,
                false,
                R.string.night_desc_hunter
            ),
            CharacterClass(
                "Ritter",
                "blabla",
                R.color.knight,
                false,
                false,
                R.string.night_desc_knight
            ),
            CharacterClass(
                "Flötenspieler",
                "blabla",
                R.color.flute,
                false,
                false,
                R.string.night_desc_flute
            ),
            CharacterClass(
                "Freunde",
                "blabla",
                R.color.friends,
                true,
                false,
                R.string.night_desc_friends
            ),
            CharacterClass(
                "Weißer Werwolf",
                "blabla",
                R.color.wwolf,
                false,
                true,
                R.string.night_desc_wolf_child
            ),
            CharacterClass(
                "Junges",
                "blabla",
                R.color.wchild,
                false,
                true,
                R.string.night_desc_wolf_child
            ),
            CharacterClass(
                "Urwolf",
                "blabla",
                R.color.urwolf,
                false,
                true,
                R.string.night_desc_wolf_child
            )
        )
    }
}